In [1]:
from pyspark.sql.types import *
from pyspark.sql.functions import *
import pyspark
import time
df = spark.createDataFrame([
    ('id_cliente-1',  'cat-1, cat-2, cat-3'),
    ('id_cliente-2',  'cat-1, cat-4, cat-5'),
    ('id_cliente-3',  'cat-6, cat-7'),
    ('id_cliente-4',  'cat-1, cat-2, cat-7, cat-10'),
    ('id_cliente-5',  'cat-8, cat-10'),
    ('id_cliente-6',  'cat-1, cat-9, cat-10'),
    ('id_cliente-7',  'cat-1, cat-4, cat-5, cat-10'),
    ('id_cliente-8',  'cat-7, cat-9'),
    ('id_cliente-9',  'cat-1'),
    ('id_cliente-10', 'cat-1, cat-2, cat-3, cat-4, cat-5, cat-6, cat-7, cat-8, cat-10')
], ['id_cliente', 'categorias'])

df2 = spark.createDataFrame([
    ('id_cliente-1',  'cat-1, cat-2, cat-3, cat-15'),
    ('id_cliente-2',  'cat-1, cat-4, cat-5, cat-11, cat-14'),
    ('id_cliente-3',  'cat-4, cat-14, cat-15'),
    ('id_cliente-4',  'cat-1, cat-2, cat-7, cat-10'),
    ('id_cliente-5',  'cat-8, cat-10, cat-11'),
    ('id_cliente-6',  'cat-1, cat-9, cat-10, cat-11, cat-13'),
    ('id_cliente-7',  'cat-1, cat-4, cat-5, cat-10'),
    ('id_cliente-8',  'cat-7, cat-9, cat-12, cat-13, cat-14'),
    ('id_cliente-9',  'cat-2'),
    ('id_cliente-10', 'cat-1, cat-2, cat-3, cat-4, cat-5, cat-6, cat-7, cat-8, cat-10')
], ['id_cliente', 'categorias'])

In [2]:
start = time.time()
# Seu script
from pyspark.sql.types import Row

df.cache()

def createColumns(line, valueMax):
    
    newLine = {}
    newLine['client-id'] = line['id_cliente']
    
    for i in range(1, valueMax + 1):
        if str(i) in str(line['categorias']):
            newLine['cat-' + str(i)] = 1
        else:
            newLine['cat-' + str(i)] = 0
        
    return Row(**newLine)


result2 = (df
           .withColumn("cat", explode(split("categorias", ",")))
           .withColumn("t", (split("cat", "-")[1]).cast("int"))
          )
valueMax =  result2.select(max(result2["t"])).take(1)[0][0]
df3 = df.rdd.map(lambda line: createColumns(line, valueMax)).toDF()


lstSelect = []
lstSelect.append('client-id')

for i in range(1, valueMax+1):
    lstSelect.append("cat-" + str(i))
    
df3.select([field_name for field_name in lstSelect]).show()


print(time.time() - start)

In [3]:
start = time.time()
# Seu script

df2.cache()

from pyspark.sql.types import Row

def createColumns(line, valueMax):
    
    newLine = {}
    newLine['client-id'] = line['id_cliente']
    
    for i in range(1, valueMax + 1):
        if str(i) in str(line['categorias']):
            newLine['cat-' + str(i)] = 1
        else:
            newLine['cat-' + str(i)] = 0
        
    return Row(**newLine)


result2 = (df2
           .withColumn("cat", explode(split("categorias", ",")))
           .withColumn("t", (split("cat", "-")[1]).cast("int"))
          )
valueMax =  result2.select(max(result2["t"])).take(1)[0][0]
dfx = df2.rdd.map(lambda line: createColumns(line, valueMax)).toDF()



lstSelect = []
lstSelect.append('client-id')

for i in range(1, valueMax+1):
    lstSelect.append("cat-" + str(i))
    
dfx.select([field_name for field_name in lstSelect]).show()



print(time.time() - start)